language: node_js
node_js:
  - node
cache: yarn
before_script: # commands to run before the build step
  - npm install -g --silent @angular/cli
script:
  - npm run lint
  - npm test
  - npm run e2e
  - npm build
notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
