language: node_js

node_js:
  - node

branches:
  only:
    - gh-pages
    - /.*/

cache:
  directories:
    - node_modules

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
  - npm test -- --single-run --no-progress

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_deploy:
  - npm run build:prod

deploy:
  local-dir: dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
