language: node_js

node_js:
  - node

cache: yarn

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
  - npm test -- --single-run --no-progress
  - npm run e2e
  - npm build --prod --aot --no-progress

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
